//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ode_db_liveEntities : DbContext
    {
        public ode_db_liveEntities()
            : base("name=ode_db_liveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_birth> tbl_birth { get; set; }
        public DbSet<tbl_branch> tbl_branch { get; set; }
        public DbSet<tbl_entrytype> tbl_entrytype { get; set; }
        public DbSet<tbl_formtype> tbl_formtype { get; set; }
        public DbSet<tbl_login_status> tbl_login_status { get; set; }
        public DbSet<tbl_reel> tbl_reel { get; set; }
        public DbSet<tbl_reg> tbl_reg { get; set; }
        public DbSet<tbl_rework> tbl_rework { get; set; }
        public DbSet<tbl_role> tbl_role { get; set; }
        public DbSet<tbl_settings> tbl_settings { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
    }
}
