//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rework
    {
        public int info_id { get; set; }
        public Nullable<int> reg_id { get; set; }
        public string Date { get; set; }
        public Nullable<int> prev_quid { get; set; }
    }
}
