//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reel
    {
        public int reel_id { get; set; }
        public string reel_name { get; set; }
        public string reel_path { get; set; }
        public string no_of_img { get; set; }
        public string form_type { get; set; }
        public Nullable<int> b_uid { get; set; }
        public string tbl_reelcol { get; set; }
        public Nullable<int> sm_id { get; set; }
        public string reel_status { get; set; }
    }
}
