//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login_status
    {
        public int info_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> Login_date { get; set; }
        public string Login_Time { get; set; }
        public string Logout_Time { get; set; }
        public string Logout_type { get; set; }
        public string user_mac_address { get; set; }
    }
}
