//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reg
    {
        public int reg_id { get; set; }
        public Nullable<int> reel_id { get; set; }
        public string start_img { get; set; }
        public string end_img { get; set; }
        public string form_type_id { get; set; }
        public string reg_name { get; set; }
        public string held_by { get; set; }
        public Nullable<int> key_uid { get; set; }
        public string tbl_regcol { get; set; }
        public Nullable<int> qc_uid { get; set; }
        public Nullable<int> final_uid { get; set; }
        public Nullable<int> vm_id { get; set; }
        public string status { get; set; }
        public Nullable<int> sm_id { get; set; }
        public string date { get; set; }
        public Nullable<int> current_entrytype { get; set; }
    }
}
