//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_birth
    {
        public int birth_id { get; set; }
        public Nullable<int> birth_entrytypeid { get; set; }
        public string birth_surname { get; set; }
        public string birth_forename { get; set; }
        public string birth_initial { get; set; }
        public string birth_year { get; set; }
        public string birth_notes { get; set; }
        public Nullable<int> reg_id { get; set; }
        public string image_name { get; set; }
        public string Initial { get; set; }
        public string mother_maiden { get; set; }
        public string duplicate_check { get; set; }
        public string duplicate_value { get; set; }
        public Nullable<int> row_no { get; set; }
    }
}
