//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public Nullable<int> user_rollid { get; set; }
        public string user_password { get; set; }
        public Nullable<int> user_man_id { get; set; }
        public string user_status { get; set; }
        public string user_mac_address { get; set; }
        public string user_fullname { get; set; }
        public string user_branch { get; set; }
    }
}
